### ISSUE TITLE
Add the proxy settings

### ISSUE THREAD

**Issue by fsbano** [RedHatOfficial/ocp4-vsphere-upi-automation#14]
Please add the proxy setting for restricted environment:

https://raw.githubusercontent.com/RedHatOfficial/ocp4-vsphere-upi-automation/master/group_vars/all.yml

```
apiVersion: v1
baseDomain: my.domain.com
proxy:
  httpProxy: http://<username>:<pswd>@<ip>:<port> 
  httpsProxy: http://<username>:<pswd>@<ip>:<port> 
  noProxy: example.com 
additionalTrustBundle: | 
    -----BEGIN CERTIFICATE-----
    <MY_TRUSTED_CA_CERT>
    -----END CERTIFICATE-----
```

Excellent job !

Regards,
Fábio Sbano
