### ISSUE TITLE
Apply patch /root/ocp4-vsphere-upi-automation/roles/static_ips/files/bootstrap-isolinux.cfg.patch error

### ISSUE THREAD

**Issue by nsu700** [RedHatOfficial/ocp4-vsphere-upi-automation#78]
Hi Experts

I got below error when building offline OCP4 on vSphere6.7, running offline-registry on helper node

error msg:
```yaml
TASK [Apply patch /root/ocp4-vsphere-upi-automation/roles/static_ips/files/bootstrap-isolinux.cfg.patch] ***************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PatchError: 2 out of 2 hunks FAILED
fatal: [localhost]: FAILED! => {"changed": false, "msg": "2 out of 2 hunks FAILED\n"}
```

How I setup the helper node:
```bash
ansible-playbook -e @vars.yaml tasks/main.yml
ansible-playbook -i staging restricted_static_ips.yml
```

My vars.yaml for helper node setup:
```
---
disk: vda
helper:
  name: "helper"
  ipaddr: "192.168.7.77"
dns:
  domain: "homelab.kdkd"
  clusterid: "ocp4"
  forwarder1: "8.8.8.8"
  forwarder2: "8.8.4.4"
dhcp:
  router: "192.168.7.1"
  bcast: "192.168.7.255"
  netmask: "255.255.255.0"
  poolstart: "192.168.7.10"
  poolend: "192.168.7.30"
  ipid: "192.168.7.0"
  netmaskid: "255.255.255.0"
bootstrap:
  name: "bootstrap"
  ipaddr: "192.168.7.20"
  macaddr: "52:54:00:60:72:67"
masters:
  - name: "master0"
    ipaddr: "192.168.7.21"
    macaddr: "52:54:00:e7:9d:67"
  - name: "master1"
    ipaddr: "192.168.7.22"
    macaddr: "52:54:00:80:16:23"
  - name: "master2"
    ipaddr: "192.168.7.23"
    macaddr: "52:54:00:d5:1c:39"
workers:
  - name: "worker0"
    ipaddr: "192.168.7.11"
    macaddr: "52:54:00:f4:26:a1"
  - name: "worker1"
    ipaddr: "192.168.7.12"
    macaddr: "52:54:00:82:90:00"
  - name: "worker2"
    ipaddr: "192.168.7.13"
    macaddr: "52:54:00:8e:10:34"
other:
  - name: "registry"
    ipaddr: "192.168.7.77"
    macaddr: "00:50:56:82:a8:ec"
```

the groups_var/all.yaml
```
helper_vm_ip: 192.168.7.77
bootstrap_ignition_url: "http://{{helper_vm_ip}}:8080/ignition/bootstrap.ign"
config:
  provider: vsphere
  base_domain: homelab.kdkd
  cluster_name: ocp4
  fips: false
  isolationMode: NetworkPolicy
  installer_ssh_key: "{{ lookup('file', '~/.ssh/ocp4.pub') }}"
  pull_secret: {"auths"...}}}
vcenter:
  ip: 192.168.31.140
  datastore: datastore1
  network: Internal Network
  service_account_username: administrator@vsphere.local
  service_account_password: I3core1024m!@#
  admin_username: administrator@vsphere.local
  admin_password: I3core1024m!@#
  datacenter: homelab
  folder_absolute_path:
  vm_power_state: poweredon
  template_name: rhcos-vmware
download:
  clients_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest
  dependencies_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/latest/latest
  govc: https://github.com/vmware/govmomi/releases/download/v0.23.0/govc_linux_amd64.gz
bootstrap_vms:
  - { name: "bootstrap", macaddr: "00:50:56:a8:aa:a1", ipaddr: "192.168.7.181", cpu: 4, ram: 16384}
master_vms:
  - { name: "master1", macaddr: "00:50:56:a8:aa:a2", ipaddr: "192.168.7.182", cpu: 4, ram: 16384}
  - { name: "master2", macaddr: "00:50:56:a8:aa:a3", ipaddr: "192.168.7.183", cpu: 4, ram: 16384}
  - { name: "master3", macaddr: "00:50:56:a8:aa:a4", ipaddr: "192.168.7.184", cpu: 4, ram: 16384}
worker_vms:
  - { name: "worker1", macaddr: "00:50:56:a8:aa:a5", ipaddr: "192.168.7.185", cpu: 4, ram: 8192}
  - { name: "worker2", macaddr: "00:50:56:a8:aa:a6", ipaddr: "192.168.7.186", cpu: 4, ram: 8192}
  - { name: "worker3", macaddr: "00:50:56:a8:aa:a7", ipaddr: "192.168.7.187", cpu: 4, ram: 8192}
static_ip:
  gateway: 192.168.7.1
  netmask: 255.255.255.0
  dns: "{{ helper_vm_ip }}"
  network_interface_name: ens224
proxy:
  enabled: false
  http_proxy: http://helper.ocp4.example.com:3129
  https_proxy: http://helper.ocp4.example.com:3129
  no_proxy: example.com
  cert_content: |
    -----BEGIN CERTIFICATE-----
        <certficate content>
    -----END CERTIFICATE-----
registry:
  enabled: true
  product_repo: openshift-release-dev
  product_release_name: ocp-release
  product_release_version: 4.6.0-x86_64
  username: ansible
  password: ansible
  email: user@awesome.org
  cert_content:
  host: registry.ocp4.homelab.kdkd
  port: 5000
  repo: ocp4/openshift4
ntp:
  custom: true
  ntp_server_list:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org
 ```

Expect the playbook running well and return me a ocp cluster
Thank you
