### ISSUE TITLE
customvalues are ignored

### ISSUE THREAD

**Issue by ddreggors** [RedHatOfficial/ocp4-vsphere-upi-automation#90]
It seems that `customvalues` are ignored now in newer versions of ansible/vmware_guest. There are no errors it just does not set the values. 

The `advanced_settings` key now successfully replaces the `customvalues` key:

```
advanced_settings:
     - key: guestinfo.ignition.config.data
       value: "{{ BootstrapContent }}"
     - key: guestinfo.ignition.config.data.encoding
       value: base64
     - key: guestinfo.afterburn.initrd.network-kargs
       value: "ip={{ item.ipaddr }}::{{ static_ip.gateway }}:{{ static_ip.netmask }}:{{ item.name }}:ens192:off:{{ static_ip.dns }}"
```
